import test from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes,scryptSync} from 'node:crypto';
import {createApp} from '../server.mjs';
const password='Account-2468!';
const adminPassword='Private admin password 2026!';
const salt=randomBytes(16).toString('hex');
const adminBootstrap={nickname:'test-admin',salt,passwordHash:scryptSync(adminPassword,salt,32).toString('hex')};
async function fixture(options={}){const app=createApp({dbPath:':memory:',adminBootstrap,...options});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;const client=()=>{let cookie='';return async(path,method='GET',data)=>{const response=await fetch(base+'/api/'+path,{method,headers:{cookie,...data?{'Content-Type':'application/json'}:{}},body:data?JSON.stringify(data):undefined});if(response.headers.get('set-cookie'))cookie=response.headers.get('set-cookie').split(';')[0];return{status:response.status,...await response.json()};};};return{app,client};}
async function record(c){const run=await c('runs','POST',{content:'memory'});const saved=await c('records','POST',{run:run.id,scopes:['world','local'],country:'대한민국',region:'서울특별시',district:'강남구',result:{value:12,display:'12',unit:'점',mode:'growing-grid-v2',details:{}}});assert.equal(saved.status,200);return saved.id;}
test('nickname login restores one owner across browsers; wrong password and duplicate signup never create a configured identity',async()=>{const{app,client}=await fixture();try{const a=client(),b=client();const created=await a('auth/register','POST',{nickname:'로그인테스트',password,role:'admin'});assert.equal(created.status,200);assert.equal(created.user.admin,false);const rid=await record(a);assert.equal((await b('auth/login','POST',{nickname:'로그인테스트',password:'wrong'})).status,403);assert.equal((await b('auth/register','POST',{nickname:'로그인테스트',password})).status,409);const logged=await b('auth/login','POST',{nickname:'로그인테스트',password});assert.equal(logged.user.id,created.user.id);assert.equal((await b('records')).records[0].id,rid);assert.equal((await a('session')).user.id,created.user.id);assert.equal((await b('records/'+rid,'DELETE',{password})).status,200);assert.equal((await a('records')).records.length,0);}finally{await app.close();}});
test('new accounts reject short credentials and reserved administrator nickname',async()=>{const{app,client}=await fixture();try{const c=client();assert.equal((await c('auth/register','POST',{nickname:'짧은암호',password:'ab3'})).status,400);assert.equal((await c('profile','POST',{nickname:'우회',pin:'123'})).status,400);assert.equal((await c('auth/register','POST',{nickname:' TEST-ADMIN ',password})).status,409);}finally{await app.close();}});
test('legacy profiles require their original session/PIN to claim login and retain records',async()=>{const{app,client}=await fixture();try{const a=client(),b=client();const guest=await a('session'),legacySalt=randomBytes(16).toString('hex');app.db.prepare('UPDATE users SET nickname=?,pin_hash=?,salt=? WHERE id=?').run('기존사람',scryptSync('2468',legacySalt,32).toString('hex'),legacySalt,guest.user.id);const rid=await record(a);assert.equal((await b('auth/login','POST',{nickname:'기존사람',password:'2468'})).status,403);assert.equal((await b('auth/register','POST',{nickname:'기존사람',password})).status,409);const upgraded=await a('auth/upgrade','POST',{nickname:'기존사람',currentPassword:'2468',password});assert.equal(upgraded.status,200);assert.equal(upgraded.user.id,guest.user.id);assert.equal((await b('auth/login','POST',{nickname:'기존사람',password})).user.id,guest.user.id);assert.equal((await b('records')).records[0].id,rid);}finally{await app.close();}});
test('only administrator can list/delete other records, password change and confirmation required, inventory untouched and audit recorded',async()=>{const{app,client}=await fixture();try{const owner=client(),stranger=client(),admin=client();await owner('auth/register','POST',{nickname:'기록주인',password});const rid=await record(owner);const room=await owner('groups','POST',{name:'관리 검증방',content:'memory',period:'all'});assert.equal(room.status,200);app.db.prepare('INSERT INTO group_records VALUES(?,?)').run(room.id,rid);const inventoryBefore=await owner('rpg');assert.equal((await stranger('admin/records')).status,403);assert.equal((await owner('admin/records/'+rid,'DELETE',{password,reason:'test',role:'admin'})).status,403);const logged=await admin('auth/login','POST',{nickname:'test-admin',password:adminPassword});assert.equal(logged.status,200);assert.equal(logged.user.admin,true);assert.equal(logged.user.mustChangePassword,true);assert.equal((await admin('admin/records')).status,403);const newPassword='Changed-2468!';assert.equal((await admin('auth/password','POST',{currentPassword:adminPassword,password:newPassword})).status,200);const rows=await admin('admin/records?q=기록주인');assert.equal(rows.records.length,1);assert.ok(!JSON.stringify(rows).includes('pin_hash'));assert.equal((await admin('admin/records/'+rid,'DELETE',{password:'wrong',reason:'중복 기록'})).status,403);assert.equal((await owner('records')).records.length,1);assert.equal((await admin('admin/records/'+rid,'DELETE',{password:newPassword,reason:'중복 기록'})).status,200);assert.equal((await owner('records')).records.length,0);assert.equal((await admin('admin/audit')).events.length,1);assert.equal(app.db.prepare('SELECT COUNT(*) AS n FROM group_records WHERE record_id=?').get(rid).n,0);assert.deepEqual(await owner('rpg'),inventoryBefore);assert.equal((await owner('profile')).user.configured,true);assert.equal((await admin('admin/records/'+rid,'DELETE',{password:newPassword,reason:'중복 기록'})).status,404);}finally{await app.close();}});
test('password changes and recovery revoke other sessions; logout only clears current browser',async()=>{const{app,client}=await fixture();try{const a=client(),b=client();const created=await a('auth/register','POST',{nickname:'세션테스트',password});await b('auth/login','POST',{nickname:'세션테스트',password});const next='Next-9753!';await a('auth/password','POST',{currentPassword:password,password:next});assert.notEqual((await b('session')).user.id,created.user.id);await b('auth/login','POST',{nickname:'세션테스트',password:next});await b('auth/logout','POST',{});assert.notEqual((await b('session')).user.id,created.user.id);assert.equal((await a('session')).user.id,created.user.id);}finally{await app.close();}});

test('recovery-code rotation revokes other browsers and preserves current session',async()=>{const{app,client}=await fixture();try{const a=client(),b=client();const created=await a('auth/register','POST',{nickname:'코드변경',password});await b('auth/login','POST',{nickname:'코드변경',password});const next=await a('auth/recovery','POST',{password});assert.equal(next.status,200);assert.notEqual(next.recovery,created.recovery);assert.equal((await a('session')).user.id,created.user.id);assert.notEqual((await b('session')).user.id,created.user.id);assert.equal((await b('recover','POST',{recovery:created.recovery,password})).status,403);assert.equal((await b('recover','POST',{recovery:next.recovery,password})).user.id,created.user.id);}finally{await app.close();}});

test('owner nickname stays reserved without bootstrap; normalized duplicates cannot bypass ownership',async()=>{const{app,client}=await fixture({adminBootstrap:null});try{const a=client(),b=client();assert.equal((await a('auth/register','POST',{nickname:'ＤＵＮＳＭＩＬＥ',password})).status,409);const created=await a('auth/register','POST',{nickname:'TestName',password});assert.equal((await b('auth/register','POST',{nickname:' testname ',password})).status,409);assert.equal((await b('auth/login','POST',{nickname:'ＴＥＳＴＮＡＭＥ',password})).user.id,created.user.id);}finally{await app.close();}});

test('administrator bootstrap is idempotent after password change and delete failure rolls back audit',async()=>{const{app,client}=await fixture();try{const admin=client(),owner=client();await owner('auth/register','POST',{nickname:'트랜잭션주인',password});const rid=await record(owner);await admin('auth/login','POST',{nickname:'test-admin',password:adminPassword});const next='Changed-9753!';await admin('auth/password','POST',{currentPassword:adminPassword,password:next});const {createAuth}=await import('../server/auth.js');createAuth(app.db,{adminBootstrap,fail:(m,s)=>{throw Object.assign(Error(m),{status:s});}});assert.equal((await admin('session')).user.mustChangePassword,false);assert.equal((await client()('auth/login','POST',{nickname:'test-admin',password:adminPassword})).status,403);assert.equal((await client()('auth/login','POST',{nickname:'test-admin',password:next})).status,200);app.db.exec("CREATE TRIGGER test_delete_failure BEFORE DELETE ON records BEGIN SELECT RAISE(ABORT,'test rollback'); END");assert.equal((await admin('admin/records/'+rid,'DELETE',{password:next,reason:'검증 삭제'})).status,500);assert.equal((await owner('records')).records.length,1);assert.equal((await admin('admin/audit')).events.length,0);}finally{await app.close();}});

test('failed login throttle survives handler recreation and client role never authorizes deletion',async()=>{const{app,client}=await fixture();try{const c=client();await c('auth/register','POST',{nickname:'시도제한',password});for(let i=0;i<10;i++)assert.equal((await c('auth/login','POST',{nickname:'시도제한',password:'wrong'})).status,403);const {createAuth}=await import('../server/auth.js');const auth=createAuth(app.db,{adminBootstrap,fail:(m,s)=>{throw Object.assign(Error(m),{status:s});}});assert.throws(()=>auth.login({nickname:'시도제한',password},'another-ip'),e=>e.status===429);}finally{await app.close();}});

test('new password length is inclusive 4–15 for registration, legacy upgrade and password changes',async()=>{const{app,client}=await fixture();try{
 const a=client();for(const password of ['aB7','aB7!cD8@eF9#gH01'])assert.equal((await a('auth/register','POST',{nickname:'길이검증',password})).status,400);
 const created=await a('auth/register','POST',{nickname:'길이검증',password:'2468'});assert.equal(created.status,200);
 const fifteen='aB7!cD8@eF9#gH0';assert.equal(fifteen.length,15);for(const password of ['aB7',fifteen+'1'])assert.equal((await a('auth/password','POST',{currentPassword:'2468',password})).status,400);
 assert.equal((await a('auth/password','POST',{currentPassword:'2468',password:fifteen})).status,200);assert.equal((await client()('auth/login','POST',{nickname:'길이검증',password:fifteen})).user.id,created.user.id);
 const b=client(),legacy=await b('session'),salt=randomBytes(16).toString('hex');app.db.prepare('UPDATE users SET nickname=?,pin_hash=?,salt=? WHERE id=?').run('기존길이',scryptSync('1357',salt,32).toString('hex'),salt,legacy.user.id);
 assert.equal((await b('auth/upgrade','POST',{nickname:'기존길이',currentPassword:'1357',password:fifteen+'1'})).status,400);assert.equal((await b('auth/upgrade','POST',{nickname:'기존길이',currentPassword:'1357',password:'Ab7!'})).status,200);
 const admin=client();assert.equal((await admin('auth/login','POST',{nickname:'test-admin',password:adminPassword})).status,200);assert.equal((await admin('auth/password','POST',{currentPassword:adminPassword,password:'New9'})).status,200);assert.equal((await admin('admin/records')).status,200);
 }finally{await app.close();}});
