const{chromium}=require('playwright');const fs=require('fs');
(async()=>{const b=await chromium.launch({headless:true});try{const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));const check=(v,m)=>{if(!v)throw Error(m)},state=()=>p.evaluate(()=>JSON.parse(window.render_game_to_text())),advance=ms=>p.evaluate(ms=>window.advanceTime(ms),ms),act=(a)=>p.locator(`[data-act="${a}"]`).first().click();
async function visit(hash,selector){await p.goto('http://localhost:4174/#/'+hash);await p.locator(selector||'#main h1').first().waitFor();}
async function start(id){await visit('play/'+id+'?seed=82','.dg-game');await advance(0);}
await visit('explore','.content-card');check(await p.locator('.content-card').count()===21,'catalog count');
await start('sort');let st=await state();const initial=st.queue[0].side;await p.keyboard.press(initial==='left'?'ArrowLeft':'ArrowRight');check((await state()).score===1,'sort key input');await p.locator('.dg-game__pause').click();await p.keyboard.press((await state()).queue[0].side==='left'?'ArrowLeft':'ArrowRight');check((await state()).score===1,'pause blocks input');await advance(1000);check((await state()).remainingMs===st.remainingMs,'pause time frozen');await p.locator('.dg-game__pause').click();await advance(21001);await p.locator('.result-number').waitFor();check((await p.locator('.result-number').textContent()).includes('1'),'sort finish');await p.screenshot({path:'tests/sort-result.png'});
await act('register');await p.locator('#register-form').waitFor();await p.locator('[name=nickname]').fill('브라우저검토');await p.locator('[name=pin]').fill('2468');await p.locator('[name=scope][value=world]').check();await p.locator('#register-form button[type=submit]').click();await p.locator('.rank-row.mine').waitFor();check((await p.locator('.rank-row.mine').textContent()).includes('1'),'registration persistent');
await start('timing');const target=(await state()).target;check(target>=1&&target<=10,'random target');await p.locator('.dg-game__primary').click();await advance(5150);await p.locator('.dg-game__primary').click();await p.locator('.result-number').waitFor();check((await p.locator('.result-number').textContent()).startsWith('5.15'),'timing 2 decimals');check(!(await p.locator('.result-card').innerText()).includes('오차'),'no timing error shown');
await start('color');for(let i=0;i<16;i++){const s=await state();check(s.gridSize===(i<2?2:i<6?3:i<10?4:5),'color stage '+i);await p.locator('.dg-game__color-cell').nth(s.targetIndex).click();}check((await state()).gridSize===6,'color sixth grid');await p.screenshot({path:'tests/color-game.png'});await advance(30001);await p.locator('.result-number').waitFor();
await start('reaction');const pad=p.locator('.dg-game__reaction');await pad.click();await pad.click();check((await state()).phase==='early','reaction early');for(let i=0;i<3;i++){await pad.click();await advance(4501);await advance(250);await pad.click();}await p.locator('.result-number').waitFor();check((await p.locator('.result-number').textContent()).includes('ms'),'reaction result');
await start('typing');st=await state();await advance(1000);await p.locator('.typing-rpg__input').fill(st.target);await p.locator('.typing-rpg__input').press('Enter');check((await state()).completed===1,'typing attack');await advance(5000);await p.screenshot({path:'tests/typing-game.png'});await advance(250000);await p.locator('.result-number').waitFor();
await start('racing');await advance(2500);await p.keyboard.press('ArrowLeft');check((await state()).lane===1,'racing lane');await p.keyboard.press('ArrowLeft');check((await state()).lane===0,'lane boundary');await p.screenshot({path:'tests/racing-game.png'});let collision=false;for(let i=0;i<40;i++){let s=await state();if(!s.vehicles){collision=true;break;}const obstacle=s.vehicles.find(e=>e.z>0);if(obstacle){while((await state()).lane<obstacle.lane)await p.keyboard.press('ArrowRight');while((await state()).lane>obstacle.lane)await p.keyboard.press('ArrowLeft');}await advance(500);}check(collision,'racing collision finish');await p.locator('.result-number').waitFor();
await start('memory');await advance(1201);st=await state();for(const idx of st.targets)await p.locator('.dg-game__memory-cell').nth(idx).click();check((await state()).completedRounds===1,'memory next round');await advance(2000);st=await state();const wrong=Array.from({length:st.gridSize*st.gridSize},(_,i)=>i).find(i=>!st.targets.includes(i));for(let i=0;i<3;i++)await p.locator('.dg-game__memory-cell').nth(wrong).click();await p.locator('.result-number').waitFor();
await start('numbers');st=await state();const expectedNumbers=((st.elapsedMs+2500)/1000).toFixed(2);for(let n=1;n<=25;n++){await advance(100);await p.locator('.dg-game__number-cell').filter({hasText:new RegExp('^'+n+'$')}).click();}await p.locator('.result-number').waitFor();check((await p.locator('.result-number').textContent()).includes(expectedNumbers),'numbers completion');
await start('sequence');await p.locator('.rhythm-game__start').click();await advance((await state()).phaseRemainingMs);await advance((await state()).phaseRemainingMs);await p.keyboard.press('Space');check((await state()).hits===1,'rhythm input');await advance(60000);await p.locator('.result-number').waitFor();
await start('jump');await p.keyboard.press('Space');await advance(200);check((await state()).player.jumps===1,'jump control');await advance(18000);await p.locator('.result-number').waitFor();
for(const [id,topic,total]of [['knowledge','flags',10],['guess','game',10],['iq','mixed',20]]){await visit(`play/${id}?seed=42&topic=${topic}`,'.answer');for(let i=0;i<total;i++){await p.locator('[data-act=answer]').first().click();await act('next');}await p.locator('.result-number').waitFor();check(await p.locator('.review-answers article').count()===total,'quiz review count '+id);}
for(const id of ['shop','energy','chat','taste','tarot','daily','character','chemistry']){await visit('play/'+id+'?seed=42','#birth-form');await p.locator('[name=name]').fill('테스트친구');if(!['chat','shop'].includes(id)){await p.locator('[name=birthday]').fill('20000515');await p.locator('[name=timeUnknown]').uncheck();await p.locator('[name=birthHour]').selectOption('14');await p.locator('[name=birthMinute]').selectOption('30');}await p.locator('#birth-form button[type=submit]').click();if(['shop','energy','chat','taste'].includes(id)){for(let i=0;i<(id==='shop'?12:8);i++)await p.locator('[data-act=answer]').nth(i%2).click();}if(id==='tarot')await p.locator('[data-act=tarot]').first().click();await p.locator('.result-card').waitFor();if(['chat','shop'].includes(id))check(await p.locator('.pillar').count()===0,'nickname only '+id);else check(await p.locator('.pillar').count()===4,'birth pillars '+id);if(id==='chemistry')await p.screenshot({path:'tests/birth-result.png',fullPage:true});}
const pages=['','explore','detail/sort','detail/knowledge','rankings?scope=world','rankings?scope=local','groups','group-new','join','my','profile','settings','recover','info/privacy'];const overflows=[];for(const width of [320,390,768,1024,1440,1920]){await p.setViewportSize({width,height:1000});for(const hash of pages){await visit(hash);const bad=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2);if(bad)overflows.push({width,hash});}}
check(!overflows.length,'overflow '+JSON.stringify(overflows));check(!errors.length,'runtime '+JSON.stringify(errors));fs.writeFileSync('tests/browser-report.json',JSON.stringify({gameFlows:10,quizFlows:3,profileFlows:8,widths:[320,390,768,1024,1440,1920],routeChecks:pages.length*6,overflows,errors,passed:true},null,2));console.log('BROWSER_FLOWS_PASSED');}finally{await b.close()}})().catch(e=>{console.error(e.stack);process.exitCode=1});
