const {chromium}=require('playwright');const fs=require('fs');
(async()=>{const b=await chromium.launch();try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.message));const check=(v,m)=>{if(!v)throw Error(m)},state=()=>p.evaluate(()=>JSON.parse(window.render_game_to_text())),advance=ms=>p.evaluate(ms=>window.advanceTime(ms),ms),last=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('dw:history'))[0]);
async function start(id){await p.goto('http://localhost:4174/#/play/'+id+'?seed=42');await p.locator('.dg-game').waitFor();await advance(0);}
async function moveTo(lane){while((await state()).lane<lane)await p.keyboard.press('ArrowRight');while((await state()).lane>lane)await p.keyboard.press('ArrowLeft');}
await start('sort');let st=await state();const next=st.queue[1],before=st.queue[0];const width=await p.locator('canvas').evaluate(e=>e.getBoundingClientRect().width);check(width>650,'sort board should be wide');await p.keyboard.press(before.side==='left'?'ArrowLeft':'ArrowRight');st=await state();check(st.score===1,'sort correct');check(st.queue[0].key===next.key&&st.queue[0].y===next.y,'next character must not jump after hit');await advance(300);check((await state()).queue[0].y>next.y,'continuous falling');await p.screenshot({path:'output/game-v2/sort-active.png'});await p.locator('.dg-game__pause').click();const paused=await state();await advance(300);await p.keyboard.press(paused.queue[0].side==='left'?'ArrowLeft':'ArrowRight');check((await state()).score===1&&(await state()).queue[0].y===paused.queue[0].y,'sort pause');await p.locator('.dg-game__pause').click();await advance(4000);check((await state()).missed>0,'missed falling character');await advance(10000);await p.locator('.result-number').waitFor();check((await last()).mode==='single-line-v3','sort result version');
await start('timing');await p.locator('.dg-game__primary').click();await advance(1230);check((await p.locator('.dg-game__timing-clock').textContent())==='1.23','live timer visible');check((await state()).clockVisible,'timer state visible');await p.screenshot({path:'output/game-v2/timing-active.png'});await p.locator('.dg-game__pause').click();await advance(1000);check((await p.locator('.dg-game__timing-clock').textContent())==='1.23','clock pause');await p.locator('.dg-game__pause').click();await advance(3920);await p.locator('.dg-game__primary').click();await p.locator('.result-number').waitFor();check((await last()).display==='5.15','stop actual time 2 decimals');check(!(await p.locator('.result-card').innerText()).includes('오차'),'no delta shown');
await start('reaction');const pad=p.locator('.dg-game__reaction');check((await state()).totalRounds===3,'three trials');await pad.click();await pad.click();check((await state()).phase==='early','early trial omitted');for(let i=0;i<3;i++){await pad.click();await advance(4600);await advance(180+i*10);if(i===1)await p.screenshot({path:'output/game-v2/reaction-active.png'});await pad.click();if(i<2)check((await state()).completedRounds===i+1,'not prematurely finished');}await p.locator('.result-number').waitFor();check((await last()).details.rounds.length===3,'exactly 3 rounds');check((await p.locator('.result-card').innerText()).includes('3회 평균'),'3 round result text');
await start('memory');check((await state()).targets.length===3,'start recall3');for(let round=1;round<=8;round++){st=await state();const size=round<4?5:round<8?6:7;check(st.gridSize===size,'memory grid stage '+round);check(await p.locator('.dg-game__memory-cell').count()===size*size,'real memory buttons');await advance(st.phaseMs+1);st=await state();if(round===8){await p.screenshot({path:'output/game-v2/memory-stage8.png'});const wrong=Array.from({length:size*size},(_,i)=>i).find(i=>!st.targets.includes(i));for(let i=0;i<3;i++)await p.locator('.dg-game__memory-cell').nth(wrong).click();break;}for(const n of st.targets)await p.locator('.dg-game__memory-cell').nth(n).click();await advance(651);}await p.locator('.result-number').waitFor();check((await last()).display==='7','memory stages completed');
await start('sequence');check(await p.locator('.dg-game__sequence-pad').count()===9,'9 real pads');await advance(450);await p.screenshot({path:'output/game-v2/sequence-active.png'});await advance(951);st=await state();await p.locator('.dg-game__sequence-pad').nth(st.sequence[0]).click();check((await state()).completedLength===1,'9-pad correct advances');await advance(2400);st=await state();await p.locator('.dg-game__sequence-pad').nth((st.sequence[0]+1)%9).click();await p.locator('.result-number').waitFor();check((await last()).mode==='nine-pad','9-pad result');
await start('racing');await advance(1300);st=await state();let item=st.entities.find(e=>e.type==='obstacle'),id=item.id,targetLane=item.lane,safeLane=[0,1,2].find(n=>n!==targetLane&&n!==1);await moveTo(safeLane);const initialX=(await state()).player.x;await advance(90);const halfway=(await state()).player.x;check(halfway!==initialX&&halfway!==((await state()).player.targetX),'smooth lane movement');await advance(100);for(let i=0;i<400;i++){await advance(16);st=await state();item=st.entities?.find(e=>e.id===id);if(item?.y>680)break;}check(item&&item.passed,'safely overtaken marked');await moveTo(targetLane);await advance(200);check((await state()).id==='racing','late lane change must not crash');await p.screenshot({path:'output/game-v2/racing-passed.png'});
await start('racing');await advance(1300);st=await state();targetLane=st.entities.find(e=>e.type==='obstacle').lane;await moveTo(targetLane);for(let i=0;i<400;i++){await advance(16);if((await state()).screen==='#/result')break;}await p.locator('.result-number').waitFor();check((await last()).mode==='fair-racing-v2','head on collision retained');
// Check all changed controls and active boards at mobile and desktop sizes.
const layouts=[];for(const [w,h]of [[320,568],[390,844],[1280,720]]){await p.setViewportSize({width:w,height:h});for(const id of ['sort','timing','reaction','racing','memory','sequence']){await start(id);const box=await p.locator('.dg-game').evaluate(e=>({bottom:e.getBoundingClientRect().bottom,width:e.getBoundingClientRect().width,overflow:document.documentElement.scrollWidth>innerWidth}));layouts.push({w,h,id,...box});check(!box.overflow,'horizontal overflow '+id);check(box.bottom<=h+1,'controls below screen '+JSON.stringify({w,h,id,...box}));await p.screenshot({path:`output/game-v2/${id}-${w}.png`});}}
check(!errors.length,JSON.stringify(errors));fs.writeFileSync('tests/game-feel-v2-report.json',JSON.stringify({passed:true,continuousSort:true,visibleTimer:true,reactionRounds:3,memoryGrids:[25,36,49],sequencePads:9,lateRacingCollisionFixed:true,headOnCollision:true,layouts,errors},null,2));console.log('GAME_FEEL_V2_PASSED');
}finally{await b.close()}})().catch(e=>{console.error(e.stack);process.exitCode=1});
