import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createApp} from '../server.mjs';import {createTypingRpgModel} from '../public/js/typing-rpg.js';import {seededRandom} from '../public/js/game-random.js';
import * as jump from '../public/js/jump-game.js';import * as oldJump from '../public/js/legacy/jump-game-v5.js';import {jumpPatterns100} from '../public/js/jump-patterns.js';import {jumpPatterns100 as oldPatterns} from '../public/js/legacy/jump-patterns-v5.js';
import {cityProjection,vehiclePassState,vehicleFootprint,laneTrafficState} from '../public/js/city-projection.js';import {cityCollision} from '../public/js/city-engine.js';

test('guest clears and items attach to a newly created profile and survive restart and recovery',async()=>{
 const folder=mkdtempSync(join(tmpdir(),'dwingul-v6-'));let app,base,cookie='';const start=async()=>{app=createApp({dbPath:join(folder,'test.sqlite')});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${app.server.address().port}`;};
 const req=async(p,data)=>{const r=await fetch(base+'/api/'+p,{method:data?'POST':'GET',headers:{cookie,'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});cookie=r.headers.get('set-cookie')?.split(';')[0]||cookie;return{status:r.status,...await r.json()};};
 try{await start();const attempt=await req('runs',{content:'typing',seed:73}),m=createTypingRpgModel({random:seededRandom('typing:73')});
  while(m.getState().stage<=14){m.tick(700);m.commitInput(m.getState().target);m.submit();if(m.getState().bestClearedStage===1){const first=await req('rpg/progress',{run:attempt.id,...m.getProgress().details,final:false});assert.equal(first.status,200);assert.equal(first.bestCleared,1);}}
  const saved=await req('rpg/progress',{run:attempt.id,...m.getProgress().details,final:false});assert.equal(saved.bestCleared,14);assert.equal(saved.gold,160);assert.deepEqual(saved.checkpoints,[1]);assert.deepEqual(saved.earnedCheckpoints,[1,11]);assert.equal(saved.configured,false);
  const draw=await req('rpg/draw',{key:'guest-draw-v6'});assert.equal(draw.status,200);await req('rpg/equip',{slot:draw.item.slot,itemId:draw.item.id});const before=await req('rpg');const result=await req('profile',{nickname:'이어가는 모험가',pin:'Test-2468-password!'});assert.ok(result.recovery);const after=await req('rpg');assert.equal(after.bestCleared,before.bestCleared);assert.equal(after.gold,before.gold);assert.deepEqual(after.owned,before.owned);assert.deepEqual(after.equipped,before.equipped);assert.equal(after.recommendedStartStage,11);
  await app.close();await start();assert.deepEqual((await req('rpg')).equipped,before.equipped);cookie='';const recovered=await req('recover',{recovery:result.recovery,pin:'Test-2468-password!'});assert.equal(recovered.status,200);assert.equal((await req('rpg')).gold,before.gold);const run=await req('runs',{content:'typing',gameSettings:{startStage:11}});assert.equal(run.status,200);assert.equal(run.gameSettings.startStage,11);assert.deepEqual(run.gameSettings.gear,before.gear);
 }finally{await app?.close();rmSync(folder,{recursive:true,force:true});}
});
function survives(e,lead,delay,speed,p){const player={y:390,vy:0,jumps:0,duck:false},ob={...e,x:158+lead*speed*e.speedScale,passed:false};p.tryJump(player);let second=false;for(let t=0;t<3;t+=.004){if(!second&&t>=delay){p.tryJump(player);second=true;}p.stepJumpPlayer(player,.004);ob.x-=speed*e.speedScale*.004;if(p.jumpCollides(player,ob))return false;if(ob.x+ob.w<108)return true;}return false;}
test('double-jump obstacles offer substantially more timing tolerance at early and maximum speed',()=>{
 const sets=[[jump,jumpPatterns100],[oldJump,oldPatterns]];const scores=sets.map(([p,patterns])=>{let successes=0,total=0;for(const e of patterns.filter(p=>p.type==='double').map(p=>p.events[0]))for(const speed of[220,420])for(const lead of[.25,.35,.45,.55,.65])for(const delay of[.08,.16,.24,.32,.4]){total++;if(survives(e,lead,delay,speed,p))successes++;}return successes/total;});assert.ok(scores[0]>.7);assert.ok(scores[0]>scores[1]*2);
 for(const e of jumpPatterns100.filter(p=>p.type==='double').map(p=>p.events[0])){assert.ok(e.h>140);const player={y:390,vy:0,jumps:0,duck:false};jump.tryJump(player);let peak=390;for(let t=0;t<1;t+=.004){jump.stepJumpPlayer(player,.004);peak=Math.min(peak,player.y);}assert.ok(390-peak<e.h-10,'one jump cannot reach the top');}
});
test('road footprints project vehicle length and safe return exactly matches rear clearance',()=>{
 const project=cityProjection(630),car={lane:2,z:0,type:'car'},bus={lane:2,z:0,type:'bus'};const a=vehicleFootprint(car,project),b=vehicleFootprint(bus,project);assert.ok(b[2].y-b[1].y>a[2].y-a[1].y);assert.ok(a[2].x-a[3].x>a[1].x-a[0].x,'near edge expands with depth');
 for(const type of['car','bus']){const length=type==='bus'?8:4;for(const delta of[-.01,.01]){const v={lane:1,type,z:-length/2-1.8+delta};const passed=delta<0;assert.equal(vehiclePassState(v)==='passed',passed);assert.equal(cityCollision(1,v),!passed);assert.equal(laneTrafficState([v],1),passed?'clear':'alongside');}}
 assert.equal(laneTrafficState([{lane:1,z:8,type:'car'}],1),'close');assert.equal(laneTrafficState([{lane:1,z:8,type:'car'}],2),'clear');
});

test('a previously started v5 race still settles through its original engine',async()=>{
 const {createCityEngine:createV5}=await import('../public/js/legacy/city-engine-v5.js');const app=createApp({dbPath:':memory:'});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${app.server.address().port}`;let cookie='';
 const req=async(p,data)=>{const r=await fetch(base+'/api/'+p,{method:'POST',headers:{cookie,'Content-Type':'application/json'},body:JSON.stringify(data)});cookie=r.headers.get('set-cookie')?.split(';')[0]||cookie;return{status:r.status,...await r.json()};};
 try{const run=await req('runs',{content:'racing',seed:4,gameSettings:{car:'basic'}});app.db.prepare('UPDATE runs SET game_settings=? WHERE id=?').run(JSON.stringify({version:'v5',car:'basic'}),run.id);const e=createV5({random:seededRandom('racing:4')});e.tick(30000);const s=e.state;assert.equal(s.ended,true);const paid=await req('garage/settle',{run:run.id,coins:s.coins,distance:Math.floor(s.distance),elapsedMs:Math.round(s.seconds*1000),inputs:s.inputs,reason:s.reason});assert.equal(paid.status,200);assert.equal(paid.earned,s.coins);}finally{await app.close();}
});
