const {chromium}=require('playwright');const fs=require('fs');
(async()=>{const b=await chromium.launch({headless:true});try{
 const a=await b.newContext({permissions:['clipboard-read','clipboard-write']}),c=await b.newContext(),p=await a.newPage(),q=await c.newPage(),errors=[];[p,q].forEach(x=>x.on('pageerror',e=>errors.push(e.message)));
 const visit=async(page,route,sel)=>{await page.goto('http://localhost:4174/#/'+route);await page.locator(sel||'#main h1').first().waitFor();},check=(x,m)=>{if(!x)throw Error(m)};
 await visit(p,'group-new','#group-form');await p.locator('[name=nickname]').fill('초대하는친구');await p.locator('[name=pin]').fill('2468');await p.locator('[name=name]').fill('우리의 국기 도전');await p.locator('[name=content]').selectOption('knowledge');await p.locator('[name=topic]').selectOption('flags');await p.locator('#group-form button[type=submit]').click();await p.locator('.code').waitFor();const code=await p.locator('.code').textContent();
 await visit(q,'join?code='+code,'#join-form');await q.locator('#join-form button[type=submit]').click();await q.locator('#join-confirm-form').waitFor();check((await q.locator('#join-confirm-form').innerText()).includes('우리의 국기 도전'),'preview room name');await q.locator('#join-confirm-form button[type=submit]').click();await q.locator('a[href*="play/knowledge"]').click();await q.locator('.answer').first().waitFor();check(q.url().includes('topic=flags'),'friend topic');for(let i=0;i<10;i++){await q.locator('[data-act=answer]').first().click();await q.locator('[data-act=next]').click();}await q.locator('[data-act=register]').click();await q.locator('[name=nickname]').fill('참여하는친구');await q.locator('[name=pin]').fill('1357');await q.locator('[name=scope][value=friends]').check();await q.locator('#register-form button[type=submit]').click();await q.locator('.rank-row.mine').waitFor();check((await q.locator('.rank-row.mine').innerText()).includes('참여하는친구'),'friend ranking');
 async function taste(page){await page.locator('[name=name]').fill('비교친구');await page.locator('[name=birthday]').fill('2000-05-15');await page.locator('#birth-form button[type=submit]').click();for(let i=0;i<8;i++)await page.locator('[data-act=answer]').first().click();await page.locator('[data-act=compareOrInvite]').waitFor();}
 await visit(p,'play/taste?seed=42','#birth-form');await taste(p);await p.locator('[data-act=compareOrInvite]').click();await p.waitForTimeout(200);const url=await p.evaluate(()=>navigator.clipboard.readText());check(url.includes('/#/s/'),'real share token');await q.goto(url);await q.locator('a[href*="play/taste"]').click();await q.locator('#birth-form').waitFor();await taste(q);await q.locator('[data-act=compareOrInvite]').click();await q.locator('dialog[open]').waitFor();check((await q.locator('dialog').innerText()).includes('8개 중 8개'),'recipient comparison');await q.locator('[data-act=close-dialog]').click();
 await visit(q,'my','[data-act=history-result]');await q.locator('[data-act=history-result]').filter({hasText:'상식'}).count();const ix=await q.locator('[data-act=history-result]').evaluateAll(es=>es.findIndex(e=>e.textContent.includes('상식')));if(ix>=0){await q.locator('[data-act=history-result]').nth(ix).click();await q.locator('.result-card').waitFor();check(await q.locator('[data-act=register]').count()===0,'past result registration hidden');}
 check(!errors.length,JSON.stringify(errors));fs.writeFileSync('tests/social-browser-report.json',JSON.stringify({roomPreview:true,friendQuizTopic:true,friendOnlyRanking:true,tasteRecipientComparison:true,errors,passed:true},null,2));console.log('SOCIAL_BROWSER_PASSED');
 }finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
