import {createLaunchTransfer} from './launch-transfer.js';
import {makePersonalityResult} from '../public/js/personality-tests.js';
import {randomBytes,createHash,scryptSync,timingSafeEqual} from 'node:crypto';
import {getQuestions,topics,questionVersion,questionMode,supportedQuestionVersions} from '../public/js/quizzes.js';
import {catalog,byId,regionMap,countries,currentGameModes} from '../public/js/catalog.js';
import { gameSettings, gameMode } from '../public/js/game-options.js';
import { createRpgStore } from '../public/js/rpg-store.js';
import {createProfileStore} from '../profile-store.mjs';
import { createGarageStore } from '../public/js/garage-store.js';
import {atomic} from '../lib/transaction.js';
const hash=x=>createHash('sha256').update(x).digest('hex');
const token=(n=24)=>randomBytes(n).toString('hex');
const eq=(a,b)=>{const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y);};
const pinHash=(pin,salt)=>scryptSync(pin,salt,32).toString('hex');
export function createApiHandler(db,{localOnly=false,localTickets={},staticHandler=(_req,res)=>{res.writeHead(404);res.end('Not found');}}={}){
 db.exec(`PRAGMA foreign_keys=ON;PRAGMA journal_mode=WAL;
 CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,token_hash TEXT UNIQUE,nickname TEXT DEFAULT '뒹굴러',pin_hash TEXT,salt TEXT,recovery_hash TEXT);
 CREATE TABLE IF NOT EXISTS runs(id TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),content TEXT,seed INTEGER,started INTEGER,finished INTEGER DEFAULT 0);
 CREATE TABLE IF NOT EXISTS records(id TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),content TEXT,value REAL,display TEXT,unit TEXT,higher INTEGER,mode TEXT,device TEXT,seed INTEGER,details TEXT,world INTEGER DEFAULT 0,local INTEGER DEFAULT 0,country TEXT,region TEXT,district TEXT,created INTEGER);
 CREATE TABLE IF NOT EXISTS groups(id TEXT PRIMARY KEY,owner TEXT REFERENCES users(id),name TEXT,content TEXT,code TEXT UNIQUE,seed INTEGER,period TEXT,created INTEGER);
 CREATE TABLE IF NOT EXISTS members(group_id TEXT REFERENCES groups(id) ON DELETE CASCADE,user_id TEXT REFERENCES users(id),joined INTEGER,excluded INTEGER DEFAULT 0,PRIMARY KEY(group_id,user_id));
 CREATE TABLE IF NOT EXISTS group_records(group_id TEXT REFERENCES groups(id) ON DELETE CASCADE,record_id TEXT REFERENCES records(id) ON DELETE CASCADE,PRIMARY KEY(group_id,record_id));
 CREATE TABLE IF NOT EXISTS shares(id TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),content TEXT,kind TEXT,seed INTEGER,payload TEXT,created INTEGER);
 CREATE INDEX IF NOT EXISTS record_lookup ON records(content,mode,created);`);
 for(const [table,column]of [['runs','topic'],['groups','topic']])if(!db.prepare('PRAGMA table_info('+table+')').all().some(c=>c.name===column))db.exec("ALTER TABLE "+table+" ADD COLUMN topic TEXT DEFAULT 'mixed'");
 for(const table of ['runs','groups'])if(!db.prepare('PRAGMA table_info('+table+')').all().some(c=>c.name==='question_version'))db.exec("ALTER TABLE "+table+" ADD COLUMN question_version TEXT DEFAULT 'v1'");
 for(const table of ['runs','groups'])if(!db.prepare('PRAGMA table_info('+table+')').all().some(c=>c.name==='game_settings'))db.exec('ALTER TABLE '+table+' ADD COLUMN game_settings TEXT DEFAULT NULL');
 db.exec("UPDATE groups SET topic='drama' WHERE content='guess' AND topic='mixed'; UPDATE runs SET topic='drama' WHERE content='guess' AND topic='mixed';");
 const get=(sql,...a)=>db.prepare(sql).get(...a),all=(sql,...a)=>db.prepare(sql).all(...a),run=(sql,...a)=>db.prepare(sql).run(...a);
 const fail=(m,status=400)=>{throw Object.assign(new Error(m),{status});};
 const garage=createGarageStore(db,fail),rpg=createRpgStore(db,fail),profiles=createProfileStore(db,fail);
 const launch=createLaunchTransfer(db,{localTickets});
 const limits=new Map();
 function limited(key,max){const now=Date.now(),entry=limits.get(key)||{n:0,until:now+60000};if(entry.until<now){entry.n=0;entry.until=now+60000;}entry.n++;limits.set(key,entry);if(entry.n>max)fail('요청이 많아요. 잠시 후 다시 시도해주세요.',429);if(limits.size>2000)for(const[k,v]of limits)if(v.until<now)limits.delete(k);}
 function member(groupId,userId){const g=get('SELECT * FROM groups WHERE id=?',groupId);if(!g)fail('종료되었거나 없는 친구방이에요.',404);const m=get('SELECT * FROM members WHERE group_id=? AND user_id=? AND excluded=0',groupId,userId);if(!m)fail('초대 코드로 먼저 참여해주세요.',403);return {...g,joined:m.joined};}
 function owner(g,u){if(g.owner!==u.id)fail('방장만 관리할 수 있어요.',403);}
 const publicUser=u=>({id:u.id,nickname:u.nickname,configured:!!u.pin_hash});
 function checkPin(u,pin){limited('pin:'+u.id,10);if(!u.pin_hash||typeof pin!=='string'||!eq(pinHash(pin,u.salt),u.pin_hash))fail('관리 PIN을 확인해주세요.',403);}
 async function body(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>(req.url==='/api/rpg/progress'?2097152:req.url==='/api/history'?1200000:req.url==='/api/garage/settle'?262144:24000))fail('입력 내용이 너무 길어요.',413);}try{return JSON.parse(raw||'{}');}catch{fail('입력 형식을 확인해주세요.');}}
 function ranks(params,u,group=null){const content=params.get('content')||group?.content||'sort';const c=byId(content);if(!c||!['game','quiz'].includes(c.cat))fail('종목을 확인해주세요.');let where=['r.content=?'],args=[content];if(group){where.push('r.id IN(SELECT gr.record_id FROM group_records gr JOIN members m ON m.group_id=gr.group_id AND m.user_id=r.user_id AND m.excluded=0 WHERE gr.group_id=?)');args.push(group.id);}else{const scope=params.get('scope')||'world';if(!['world','local'].includes(scope))fail('랭킹 범위를 확인해주세요.');where.push('r.'+scope+'=1');if(scope==='world'&&params.get('country')){where.push('r.country=?');args.push(params.get('country'));}if(scope==='local'){if(params.get('region')){where.push('r.region=?');args.push(params.get('region'));}if(params.get('district')){where.push('r.district=?');args.push(params.get('district'));}}}
 const mode=group?.game_settings&&gameMode(group.content,JSON.parse(group.game_settings))||params.get('mode');if(mode){where.push('r.mode=?');args.push(mode);}const device=params.get('device');if(device){where.push('r.device=?');args.push(device);}if((group?.period||params.get('period'))==='week'){const d=new Date(Date.now()+9*3600000);const day=(d.getUTCDay()+6)%7;d.setUTCDate(d.getUTCDate()-day);d.setUTCHours(0,0,0,0);where.push('r.created>=?');args.push(d.getTime()-9*3600000);}
 const rows=all(`SELECT r.*,u.nickname FROM records r JOIN users u ON u.id=r.user_id WHERE ${where.join(' AND ')}`, ...args);
 // Separate incompatible modes; no cross-mode combined rank.
 const modes=[...new Set(rows.map(r=>r.mode))].sort();const preferred=content==='timing'?modes.find(x=>x.startsWith('visible-target-')):currentGameModes[content]||(content==='iq'?'random-20-v3':content==='guess'?modes.find(x=>x.endsWith('-initials-v8')):null);const fallback={sort:['single-line-v3','falling-v2'],typing:['phrases-100-v3'],racing:['fair-racing-v2'],jump:['jump-v1']}[content]?.find(m=>modes.includes(m));const selected=mode||(modes.includes(preferred)?preferred:fallback||modes[0])||'';const comparable=rows.filter(r=>r.mode===selected);const best=new Map();for(const r of comparable){const prev=best.get(r.user_id);if(!prev||(r.higher?r.value>prev.value:r.value<prev.value))best.set(r.user_id,r);}
 const list=[...best.values()].sort((a,b)=>(a.higher?b.value-a.value:a.value-b.value)||a.created-b.created);return {mode:selected,modes,count:list.length,rows:list.slice(0,100).map((r,i)=>({id:r.id,rank:list.findIndex(x=>x.value===r.value)+1,nickname:r.nickname,display:r.display,unit:r.unit,country:r.country,region:r.region,district:r.district,device:r.device,me:r.user_id===u.id})),selfRank:list.findIndex(r=>r.user_id===u.id)+1};}
 return async(req,res)=>{let headers={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'};const send=(data,status=200)=>{res.writeHead(status,headers);res.end(JSON.stringify(data));};try{
 const origin=req.origin||`http://${req.headers.host}`,url=new URL(req.url,origin),p=url.pathname,method=req.method;
 if(localOnly&&!['127.0.0.1','localhost','[::1]'].includes(url.hostname))fail('로컬 주소로 접속해주세요.',403);
 if(!p.startsWith('/api/')){await staticHandler(req,res);return;}
 if(!['GET','HEAD'].includes(method)&&(req.headers['sec-fetch-site']==='cross-site'||(req.headers.origin&&req.headers.origin!==origin)))fail('요청 출처가 일치하지 않아요.',403);
 if(p==='/api/launch-transfer/claim'&&method==='POST'){limited('transfer:'+req.socket.remoteAddress,10);const transferData=await body(req);const claimed=launch.claim(transferData.ticket);headers['Set-Cookie']=`dw_session=${claimed.secret}; HttpOnly; SameSite=Strict; Path=/; Max-Age=31536000${origin.startsWith('https:')?'; Secure':''}`;send({user:claimed.user});return;}
 const cookie=/(?:^|;\s*)dw_session=([a-f0-9]{48})/.exec(req.headers.cookie||'')?.[1];let u=cookie?get('SELECT * FROM users WHERE token_hash=?',hash(cookie)):null;
 if(!u){limited('new:'+req.socket.remoteAddress,30);const secret=token(),id=token(12);run('INSERT INTO users(id,token_hash) VALUES(?,?)',id,hash(secret));u=get('SELECT * FROM users WHERE id=?',id);headers['Set-Cookie']=`dw_session=${secret}; HttpOnly; SameSite=Strict; Path=/; Max-Age=31536000${origin.startsWith('https:')?'; Secure':''}`;}
 limited('requests:'+u.id,240);const data=['POST','PUT','DELETE'].includes(method)?await body(req):{};
 if(p==='/api/launch-transfer'&&localOnly){const ticket=launch.localTicket(u.id);send(method==='POST'?ticket||{available:false}:{available:!!ticket});return;}
 if(p==='/api/session'&&method==='GET'){send({user:publicUser(u)});return;}
 if(p==='/api/profile'&&method==='POST'){const nickname=String(data.nickname||'').trim();if(nickname.length<1||nickname.length>12)fail('닉네임은 1~12자로 입력해주세요.');let recovery=null;if(!u.pin_hash){if(!/^\d{4}$/.test(data.pin||''))fail('숫자 4자리 관리 PIN을 입력해주세요.');const salt=token(16);recovery=token(16);run('UPDATE users SET nickname=?,pin_hash=?,salt=?,recovery_hash=? WHERE id=?',nickname,pinHash(data.pin,salt),salt,hash(recovery),u.id);}else{checkPin(u,data.pin);run('UPDATE users SET nickname=? WHERE id=?',nickname,u.id);}send({user:publicUser(get('SELECT * FROM users WHERE id=?',u.id)),recovery});return;}
 if(p==='/api/recover'&&method==='POST'){limited('recover:'+req.socket.remoteAddress,10);const existing=get('SELECT * FROM users WHERE recovery_hash=?',hash(String(data.recovery||'')));if(!existing)fail('복구 코드와 PIN을 확인해주세요.',403);checkPin(existing,data.pin);const secret=token();run('UPDATE users SET token_hash=? WHERE id=?',hash(secret),existing.id);headers['Set-Cookie']=`dw_session=${secret}; HttpOnly; SameSite=Strict; Path=/; Max-Age=31536000${origin.startsWith('https:')?'; Secure':''}`;send({user:publicUser(existing)});return;}
 if(p==='/api/profile'&&method==='GET'){send({user:publicUser(u),...profiles.state(u)});return;}
 if(p==='/api/profile/birth'&&method==='PUT'){send(profiles.saveBirth(u,data));return;}
 if(p==='/api/profile/birth'&&method==='DELETE'){send(profiles.clearBirth(u));return;}
 if(p==='/api/history'&&method==='POST'){send(profiles.saveHistory(u,data));return;}
 if(p==='/api/history'&&method==='DELETE'){send(profiles.clearHistory(u));return;}
 if(p==='/api/rpg'&&method==='GET'){send(rpg.profile(u));return;}
 if(p==='/api/rpg/draw'&&method==='POST'){send(rpg.draw(u,data));return;}
 if(p==='/api/rpg/character/purchase'&&method==='POST'){send(rpg.purchaseCharacter(u,data));return;}
 if(p==='/api/rpg/character/equip'&&method==='POST'){send(rpg.equipCharacter(u,data));return;}
 if(p==='/api/rpg/equip'&&method==='POST'){send(rpg.equip(u,data));return;}
 if(p==='/api/rpg/enhance'&&method==='POST'){send(rpg.enhance(u,data));return;}
 if(p==='/api/rpg/discard'&&method==='POST'){send(rpg.discard(u,data));return;}
 if(p==='/api/rpg/progress'&&method==='POST'){send(rpg.progress(u,data));return;}
 if(p==='/api/garage'&&method==='GET'){send(garage.wallet(u.id));return;}
 if(p==='/api/garage/unlock'&&method==='POST'){send(garage.unlock(u.id,data.car));return;}
 if(p==='/api/garage/settle'&&method==='POST'){send(garage.settle(u.id,data));return;}
 if(/^\/api\/runs\/[a-zA-Z0-9_-]+$/.test(p)&&method==='DELETE'){const id=p.split('/').pop();run('DELETE FROM runs WHERE id=? AND user_id=? AND finished=0 AND NOT EXISTS(SELECT 1 FROM rpg_progress WHERE run_id=runs.id) AND NOT EXISTS(SELECT 1 FROM run_rewards WHERE run_id=runs.id)',id,u.id);send({ok:true});return;}
 if(p==='/api/runs'&&method==='POST'){
  const c=byId(data.content);if(c?.retired)fail('운영이 종료된 게임이에요.',410);if(!c||!['game','quiz'].includes(c.cat))fail('기록할 수 없는 콘텐츠예요.');
  let seed=Number.isSafeInteger(data.seed)?data.seed>>>0:randomBytes(4).readUInt32BE(),version=data.questionVersion||'v1',topic=topics[c.id]&&Object.hasOwn(topics[c.id],data.topic)?data.topic:c.id==='guess'?'drama':'mixed';
  let settings=data.gameSettings===undefined&&c.id!=='sequence'?null:gameSettings(c.id,data.gameSettings);
  if(data.groupId){const g=member(String(data.groupId),u.id);if(g.content!==c.id)fail('친구방 종목을 확인해주세요.');if(['sort','typing','racing','jump','sequence'].includes(c.id)&&JSON.parse(g.game_settings||'{}').version!==gameSettings(c.id).version)fail('게임 규칙이 바뀌었어요. 새 친구방에서 시작해주세요.');seed=g.seed;version=g.question_version;topic=g.topic;settings=gameSettings(c.id,g.game_settings?JSON.parse(g.game_settings):{});}
  if(data.shareId&&data.groupId)fail('친구방과 공유 도전 중 하나로 시작해주세요.');
  if(data.shareId){const share=get('SELECT * FROM shares WHERE id=?',String(data.shareId));if(!share||share.content!==c.id||Date.now()-share.created>30*86400000)fail('공유 조건을 찾을 수 없어요.');const payload=JSON.parse(share.payload);if(['sort','typing','racing','jump','sequence'].includes(c.id)&&payload.gameSettings?.version!==gameSettings(c.id).version)fail('게임 규칙이 바뀌었어요. 새 도전장을 만들어주세요.');seed=share.seed;settings=gameSettings(c.id,payload.gameSettings);topic=payload.category||topic;version=payload.questionVersion||version;}
  if(c.cat==='quiz'&&!supportedQuestionVersions(c.id).includes(version))fail('문제 구성이 업데이트됐어요. 새로고침 후 다시 시작해주세요.');
  if(data.gameSettings?.version&&data.gameSettings.version!==gameSettings(c.id).version&&['sort','racing','typing','jump','sequence'].includes(c.id))fail('게임이 업데이트됐어요. 새로고침 후 시작해주세요.');
  if(c.id==='typing')settings=rpg.settings(u,settings||{},!!(data.groupId||data.shareId));
  if(c.id==='racing'&&settings)garage.requireCar(u.id,settings.car);
  const id=token(12);run('INSERT INTO runs(id,user_id,content,seed,started,topic,question_version,game_settings)VALUES(?,?,?,?,?,?,?,?)',id,u.id,c.id,seed,Date.now(),topic,version,settings?JSON.stringify(settings):null);send({id,seed,questionVersion:version,topic,gameSettings:settings});return;}
 if(p==='/api/records'&&method==='POST'){if(!u.pin_hash)fail('먼저 닉네임과 관리 PIN을 설정해주세요.');const attempt=get('SELECT * FROM runs WHERE id=? AND user_id=?',data.run,u.id);if(!attempt||attempt.finished)fail('등록할 플레이를 찾을 수 없거나 이미 등록했어요.');if(attempt.game_settings&&['sort','typing','racing','jump'].includes(attempt.content)&&!['v4','v5','v6','v7','v11','v13'].includes(JSON.parse(attempt.game_settings).version))fail('게임 규칙이 바뀌었어요. 새로 플레이해주세요.');const scopes=Array.isArray(data.scopes)?data.scopes:[];if(!scopes.length||scopes.some(s=>!['world','local','friends'].includes(s)))fail('등록할 범위를 선택해주세요.');const c=byId(attempt.content),d=data.result||{},details=d.details||{};let value=Number(d.value);if(c.id==='typing'&&JSON.parse(attempt.game_settings||'{}').version==='v5'){const saved=get('SELECT score,finished FROM rpg_progress WHERE run_id=?',attempt.id);if(!saved?.finished)fail('모험 정산을 완료한 뒤 기록을 등록해주세요.');value=saved.score;}if(c.id==='racing'&&attempt.game_settings){const settled=get('SELECT distance FROM run_rewards WHERE run_id=?',attempt.id);if(!settled)fail('주행 정산이 완료된 뒤 기록을 등록해주세요.');value=settled.distance;}if(!Number.isFinite(value)||value<0||value>1000000)fail('기록 값을 확인해주세요.');if(c.cat==='quiz'){const questions=getQuestions(c.id,attempt.topic,attempt.seed,attempt.question_version);if(!Array.isArray(details.answers)||details.answers.length!==questions.length||details.answers.some(a=>!Number.isInteger(a)||a<0||a>3))fail('퀴즈 답변을 확인해주세요.');value=questions.reduce((n,q,i)=>n+(q.answer===details.answers[i]),0);}if(c.id==='sort'&&value>500&&(!attempt.game_settings||gameSettings(c.id,JSON.parse(attempt.game_settings)).mode!=='endless'))fail('검토가 필요한 기록이에요.');if(c.id==='color'&&value>150)fail('검토가 필요한 기록이에요.');let mode=String(d.mode||'standard').slice(0,60),display=String(d.display??value).slice(0,32),unit=String(d.unit||'').slice(0,12);const higher=!['timing','reaction','numbers'].includes(c.id);if(!attempt.game_settings&&/-v(?:4|5|6|7|9|11|13)(?:-|$)/.test(mode))fail('새 게임 모드로 다시 시작해주세요.');if(c.cat==='quiz'){mode=questionMode(c.id,attempt.topic,attempt.question_version);display=String(value);unit=' / '+(c.id==='iq'?20:10);}if(c.id==='timing'){const target=Number(details.target),stopped=Number(details.stoppedSeconds);if(!Number.isInteger(target)||target<1||target>10||!Number.isFinite(stopped)||stopped<0||stopped>16)fail('시간 기록을 확인해주세요.');value=Math.abs(stopped-target);display=stopped.toFixed(2);unit='초';mode=d.mode===`visible-target-${target}-v2`?d.mode:'target-'+target;}
 if(attempt.game_settings&&gameMode(c.id,JSON.parse(attempt.game_settings))){mode=gameMode(c.id,JSON.parse(attempt.game_settings));value=c.id==='jump'?Math.round(value*10)/10:Math.floor(value);display=String(value);unit=['racing','jump'].includes(c.id)?'m':c.id==='sort'?'명':mode.startsWith('typing-rpg')||mode.startsWith('rhythm-')?'점':mode==='nine-pad'?'단계':'개';if(mode==='typing-rain-v4'&&value>100)fail('문장 기록을 확인해주세요.');}
 const country=scopes.includes('world')?String(data.country||''):null,region=scopes.includes('local')?String(data.region||''):null,district=scopes.includes('local')?String(data.district||''):null;if(scopes.includes('world')&&!countries.includes(country))fail('표시 국가를 선택해주세요.');if(scopes.includes('local')&&!regionMap[region]?.includes(district))fail('지역을 선택해주세요.');let group=null;if(scopes.includes('friends')){group=member(String(data.groupId||''),u.id);if(group.content!==c.id||attempt.seed!==group.seed||attempt.started<group.joined||(c.cat==='quiz'&&(attempt.topic!==group.topic||attempt.question_version!==group.question_version))||(c.cat==='game'&&JSON.stringify(gameSettings(c.id,JSON.parse(attempt.game_settings||'{}')))!==JSON.stringify(gameSettings(c.id,JSON.parse(group.game_settings||'{}')))))fail('친구방에서 같은 조건으로 새로 플레이해주세요.');}
 const id=token(12);atomic(db,()=>{run('INSERT INTO records VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',id,u.id,c.id,value,display,unit,higher?1:0,mode,data.device==='touch'?'touch':'keyboard',attempt.seed,JSON.stringify({target:details.target,stoppedSeconds:details.stoppedSeconds,gameSettings:attempt.game_settings?JSON.parse(attempt.game_settings):null,distance:Number(details.distance)||0,coins:Number(details.coins)||0,reason:String(details.reason||'').slice(0,30)}),scopes.includes('world')?1:0,scopes.includes('local')?1:0,country,region,district,Date.now());if(group)run('INSERT INTO group_records VALUES(?,?)',group.id,id);run('UPDATE runs SET finished=1 WHERE id=?',attempt.id);});send({id});return;}
 if(p==='/api/records'&&method==='GET'){send({records:all('SELECT id,content,display,unit,mode,world,local,created FROM records WHERE user_id=? ORDER BY created DESC LIMIT 100',u.id)});return;}
 if(/^\/api\/records\/[^/]+$/.test(p)&&method==='DELETE'){checkPin(u,data.pin);run('DELETE FROM records WHERE id=? AND user_id=?',p.split('/')[3],u.id);send({ok:true});return;}
 if(p==='/api/rankings'&&method==='GET'){send(ranks(url.searchParams,u));return;}
 if(p==='/api/groups'&&method==='GET'){send({groups:all('SELECT g.*,g.owner=? AS isOwner FROM groups g JOIN members m ON g.id=m.group_id WHERE m.user_id=? AND m.excluded=0 ORDER BY g.created DESC',u.id,u.id)});return;}
 if(p==='/api/groups'&&method==='POST'){if(!u.pin_hash)fail('먼저 닉네임과 관리 PIN을 설정해주세요.');const name=String(data.name||'').trim(),c=byId(data.content);if(c?.retired)fail('운영이 종료된 게임이에요.',410);if(!name||name.length>24||!c||!['game','quiz'].includes(c.cat))fail('친구방 이름과 종목을 확인해주세요.');if(data.gameSettings?.version&&data.gameSettings.version!==gameSettings(c.id).version&&['sort','racing','typing','jump','sequence'].includes(c.id))fail('게임 규칙이 바뀌었어요. 새 설정으로 친구방을 만들어주세요.');const settings=c.id==='typing'?rpg.settings(u,{},true):['sort','racing','jump','sequence'].includes(c.id)?gameSettings(c.id,data.gameSettings):data.gameSettings===undefined?null:gameSettings(c.id,data.gameSettings);if(c.id==='racing'&&settings)garage.requireCar(u.id,settings.car);const id=token(12),seed=randomBytes(4).readUInt32BE(),created=Date.now(),code=token(4).toUpperCase();run('INSERT INTO groups(id,owner,name,content,code,seed,period,created,topic,question_version,game_settings) VALUES(?,?,?,?,?,?,?,?,?,?,?)',id,u.id,name,c.id,code,seed,data.period==='all'?'all':'week',created,topics[c.id]&&Object.hasOwn(topics[c.id],data.topic)?data.topic:c.id==='guess'?'drama':'mixed',questionVersion(c.id),settings?JSON.stringify(settings):null);run('INSERT INTO members VALUES(?,?,?,0)',id,u.id,created);send({id,code});return;}
 if(p==='/api/groups/preview'&&method==='POST'){const g=get('SELECT * FROM groups WHERE code=?',String(data.code||'').trim().toUpperCase());if(!g)fail('초대 코드가 바뀌었거나 친구방이 종료됐어요.',404);if(byId(g.content)?.retired)fail('운영이 종료된 게임의 친구방이에요.',410);const m=get('SELECT * FROM members WHERE group_id=? AND user_id=?',g.id,u.id);if(m?.excluded)fail('이 방에 참여할 수 없어요.',403);send({name:g.name,content:g.content,topic:g.topic,period:g.period,joined:!!m});return;}
 if(p==='/api/groups/join'&&method==='POST'){const g=get('SELECT * FROM groups WHERE code=?',String(data.code||'').trim().toUpperCase());if(!g)fail('초대 코드가 바뀌었거나 친구방이 종료됐어요.',404);if(byId(g.content)?.retired)fail('운영이 종료된 게임의 친구방이에요.',410);const m=get('SELECT * FROM members WHERE group_id=? AND user_id=?',g.id,u.id);if(m?.excluded)fail('이 방에 참여할 수 없어요.',403);if(!m)run('INSERT INTO members VALUES(?,?,?,0)',g.id,u.id,Date.now());send({id:g.id});return;}
 const groupMatch=p.match(/^\/api\/groups\/([^/]+)(?:\/(.*))?$/);if(groupMatch){const [,id,action]=groupMatch,g=member(id,u.id);if(!action&&method==='GET'){send({group:{...g,isOwner:g.owner===u.id},members:all('SELECT u.id,u.nickname,g.owner=u.id AS owner FROM members m JOIN users u ON u.id=m.user_id JOIN groups g ON g.id=m.group_id WHERE m.group_id=? AND m.excluded=0',id),ranking:ranks(new URLSearchParams({...Object.fromEntries(url.searchParams),content:g.content}),u,g)});return;}if(action==='withdraw'&&method==='POST'){run('DELETE FROM group_records WHERE group_id=? AND record_id IN(SELECT id FROM records WHERE user_id=?)',id,u.id);send({ok:true});return;}if(action==='leave'&&method==='POST'){if(g.owner===u.id)fail('방장은 친구방 삭제를 이용해주세요.');run('DELETE FROM group_records WHERE group_id=? AND record_id IN(SELECT id FROM records WHERE user_id=?)',id,u.id);run('DELETE FROM members WHERE group_id=? AND user_id=?',id,u.id);send({ok:true});return;}owner(g,u);if(action==='exclude'&&method==='POST'){if(data.userId===u.id)fail('방장 본인을 제외할 수 없어요.');run('UPDATE members SET excluded=1 WHERE group_id=? AND user_id=?',id,String(data.userId));run('DELETE FROM group_records WHERE group_id=? AND record_id IN(SELECT id FROM records WHERE user_id=?)',id,String(data.userId));send({ok:true});return;}if(action==='rotate'&&method==='POST'){const code=token(4).toUpperCase();run('UPDATE groups SET code=? WHERE id=?',code,id);send({code});return;}if(!action&&method==='DELETE'){run('DELETE FROM groups WHERE id=?',id);send({ok:true});return;}}
 if(p==='/api/shares'&&method==='POST'){if(byId(data.content)?.retired&&data.kind==='challenge')fail('운영이 종료된 게임이에요.',410);if(!byId(data.content))fail('콘텐츠를 확인해주세요.');const payload=data.payload||{};if(data.kind==='challenge'&&payload.gameSettings?.version&&payload.gameSettings.version!==gameSettings(data.content).version&&['sort','racing','typing','jump','sequence'].includes(data.content))fail('게임 규칙이 바뀌었어요. 새 설정으로 도전장을 만들어주세요.');const safe={name:String(payload.name||u.nickname).slice(0,12),title:String(payload.title||'').slice(0,100),display:String(payload.display||'').slice(0,32),unit:String(payload.unit||'').slice(0,12),element:String(payload.element||'').slice(0,10),scores:Array.isArray(payload.scores)?payload.scores.slice(0,8).map(Number):[],answers:data.kind==='challenge'&&data.content==='taste'&&Array.isArray(payload.answers)?payload.answers.slice(0,12).map(Number):[],theme:String(payload.theme||'').slice(0,20),category:String(payload.category||'').slice(0,24),gameSettings:data.content==='typing'?rpg.settings(u,{},true):gameSettings(data.content,payload.gameSettings),questionVersion:supportedQuestionVersions(data.content).includes(payload.questionVersion)?payload.questionVersion:'v1'};safe.content=data.content;safe.testVersion=data.content==='energy'&&payload.testVersion==='teto-egen-v13'?'teto-egen-v13':payload.testVersion==='axes-v9'?'axes-v9':'legacy-v8';if(data.content==='taste'&&data.kind==='challenge'){const expected=safe.testVersion==='axes-v9'?12:8;if(safe.answers.length!==expected||safe.answers.some(a=>a!==0&&a!==1))fail('취향 답변을 확인해주세요.');if(safe.testVersion==='axes-v9'){const r=makePersonalityResult('taste',safe.name,safe.answers);safe.personality=r.personality;safe.sprite=r.sprite;}}const id=token(12),seed=Number(data.seed)>>>0;run('INSERT INTO shares VALUES(?,?,?,?,?,?,?)',id,u.id,data.content,data.kind==='challenge'?'challenge':'result',seed,JSON.stringify(safe),Date.now());send({id});return;}
 if(p.startsWith('/api/shares/')&&method==='GET'){const row=get('SELECT content,kind,seed,payload,created FROM shares WHERE id=?',p.split('/')[3]);if(!row||Date.now()-row.created>30*86400000)fail('만료되었거나 없는 공유 링크예요.',404);const payload=JSON.parse(row.payload);payload.content=row.content;send({...row,payload});return;}
 fail('요청한 기능을 찾을 수 없어요.',404);
 }catch(e){if(!e.status)console.error(e);send({error:e.status?e.message:'처리 중 문제가 생겼어요. 다시 시도해주세요.'},e.status||500);}};
}
