import {DatabaseSync} from 'node:sqlite';
import {mkdirSync,copyFileSync,writeFileSync,existsSync,chmodSync} from 'node:fs';
import {createHash,randomBytes} from 'node:crypto';
import path from 'node:path';
import {createApiHandler} from '../server/api.js';
import {seedLaunchTransfers} from '../server/launch-transfer.js';

const source=process.argv[2],destination=process.argv[3];
if(!source||!destination)throw Error('Usage: node scripts/prepare-launch.mjs <source.sqlite> <new-data-directory>');
const directory=path.resolve(destination),target=path.join(directory,'dwingul.sqlite');
if(existsSync(target))throw Error('Destination database already exists; refusing to overwrite.');
mkdirSync(directory,{recursive:true});
const original=new DatabaseSync(path.resolve(source),{readOnly:true});
original.prepare('VACUUM INTO ?').run(target);original.close();
copyFileSync(target,path.join(directory,'before-v9.sqlite'));
const db=new DatabaseSync(target);createApiHandler(db);
const tickets=seedLaunchTransfers(db);
writeFileSync(path.join(directory,'launch-tickets.json'),JSON.stringify(tickets),{mode:0o600});
const tables={};
for(const {name}of db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").all())tables[name]=db.prepare('SELECT * FROM '+name).all();
db.close();
const snapshot=JSON.stringify({version:1,tables});
if(Buffer.byteLength(snapshot)>10*1024*1024||Object.values(tables).some(rows=>rows.length>50000))throw Error('Snapshot exceeds import limits.');
writeFileSync(path.join(directory,'launch-snapshot.json'),snapshot,{mode:0o600});
writeFileSync(path.join(directory,'migration-secret'),randomBytes(32).toString('hex'),{mode:0o600});
for(const file of ['dwingul.sqlite','before-v9.sqlite'])chmodSync(path.join(directory,file),0o600);
const report={created:new Date().toISOString(),bytes:Buffer.byteLength(snapshot),sha256:createHash('sha256').update(snapshot).digest('hex'),counts:Object.fromEntries(Object.entries(tables).map(([name,rows])=>[name,rows.length]))};
writeFileSync(path.join(directory,'launch-report.json'),JSON.stringify(report,null,2),{mode:0o600});
console.log(JSON.stringify(report,null,2));
